[Service]
Environment=ATMOSLINK_STATION=CU01
Environment=PYTHONUNBUFFERED=1
Environment=ATMOSLINK_WIND_ENABLED=1
Environment=ATMOSLINK_WIND_PORT=/dev/serial/by-id/usb-1a86_USB_Serial-if00-port0
Environment=ATMOSLINK_WIND_BAUDRATE=9600
Environment=ATMOSLINK_WIND_SLAVE_ID=1
Environment=ATMOSLINK_WIND_TIMEOUT=2.0
